--Menu
INSERT INTO TB_CATEGORY(CTG_NAME,CTG_URL,CTG_ICON) VALUES ('Tshirts','tshits','loyalty');
INSERT INTO TB_CATEGORY(CTG_NAME,CTG_URL,CTG_ICON) VALUES ('Glasses','glasses','free_breakfast');
INSERT INTO TB_CATEGORY(CTG_NAME,CTG_URL,CTG_ICON) VALUES ('Comics','comics','bookmarks');
INSERT INTO TB_CATEGORY(CTG_NAME,CTG_URL,CTG_ICON) VALUES ('Toys','toys','toys');
INSERT INTO TB_CATEGORY(CTG_NAME,CTG_URL,CTG_ICON) VALUES ('Accessories','accessories','loyalty');
INSERT INTO TB_CATEGORY(CTG_NAME,CTG_URL,CTG_ICON) VALUES ('Others','others','dynamic_feed');
INSERT INTO TB_CATEGORY(CTG_NAME,CTG_URL,CTG_ICON) VALUES ('Add Inventory','inventory','playlist_add');

--Tshirts by default
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','40,000','Tshirt #123','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','40,000','Tshirt #123','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','40,000','Tshirt #123','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','40,000','Tshirt #123','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','50,000','Tshirt #423','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','50,000','Tshirt #423','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','50,000','Tshirt #423','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','20,000','Tshirt #1233','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','60,0000','Tshirt #15343','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','20,000','Tshirt #1233','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','60,0000','Tshirt #15343','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','40,000','Tshirt #14323','1');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','70,000','Tshirt #1235','1');

--Glasses by default
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','30,000','Glasses #1223','2');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','20,000','Glasses #4423','2');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','10,000','Glasses #1233','2');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','40,0000','Glasses #11143','2');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','30,000','Glasses #11323','2');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','50,000','Glasses #22235','2');

--Comics by default
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','40,000','Comics #123','3');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','50,000','Comics #423','3');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','20,000','Comics #1233','3');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','60,0000','Comics #15343','3');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','40,000','Comics #14323','3');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','70,000','Comics #1235','3');

--Toys by default
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','40,000','Toys #2256','4');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','50,000','Toys #889','4');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','20,000','Toys #5589','4');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','60,0000','Toys #4486','4');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','40,000','Toys #9998','4');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','70,000','Toys #1256','4');

--Accessories by default
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','40,000','Accessories #7569','5');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','50,000','Accessories #12478','5');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','20,000','Accessories #853','5');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','60,0000','Accessories #8695','5');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','40,000','Accessories #1245','5');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','70,000','Accessories #4536','5');

--Others by default
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','40,000','Others #13','6');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Marvel','50,000','Others #23','6');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','20,000','Others #133','6');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('DC','60,0000','Others #1343','6');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','40,000','Others #1433','6');
INSERT INTO TB_ARTICLE(ART_BRAND,ART_PRICE,ART_REFERENCE,CATEGORY_ID) VALUES ('Other','70,000','Others #135','6');
